### ISSUE TITLE
Multiple Websites

### ISSUE THREAD

**Issue by ghost** [Cldfire/Forum-Notifier#2]
Hey,
This is a small suggestion. I think it should be possible to put multiple XenForo websites / accounts on it. So, I could put both my MacRumors account and my Spigot account. I additionally could put both my normal Spigot account and my two alternate Spigot accounts. 

Just a small suggestion so we do not have to install six different versions of this (I have about 8 XenForo accounts/sites I use on a daily basis).

Cheers,
Saphiria

**Comment by Cldfire** [comment]
This is already planned.

Is MacRumors a XenForo site? O.o

**Comment by ghost** [comment]
Yes! Probably the main reason I signed up. I love their add-on (probably custom) that lets them post very neat news articles with the comments. 

Glad to hear it is planned! 👍 I have a lot of Spigot accounts and it will be nice to know when I need to check the alts.

**Comment by ScruffyRules** [comment]
Added the ability to add multiple accounts from #9, just not implemented elsewhere.

**Comment by Cldfire** [comment]
UI now supports multiple accounts. 

EDIT: When I fix it :D

**Comment by Cldfire** [comment]
This is pretty much fully implemented at this point, closing issue.
