### ISSUE TITLE
Support more forum types and sites

### ISSUE THREAD

**Issue by Cldfire** [Cldfire/Forum-Notifier#21]
This will be something we'll constantly be working on up until (and after) the 1.0 release. Once the structure is in place, it shouldn't be too hard to add support for any number of other forums (as long as they aren't out of the ordinary, just get the xpaths for required elements and add them to the relevant methods). As such, this is something that pretty much anyone can jump in an help with; it's a time-consuming process that will go much faster with more people helping. 

Some forum types we should work on supporting **(see README.md).**

Things that need to get done before we can do this:
- [ ] Add way to select forum type when adding a new forum
- [ ] Structure the login / information-grabbing systems to allow for easy adaptation for use with other sites (ideally make it as easy as adding an xpath to a list)

**Comment by ctian1** [comment]
- [ ] Discourse? (https://www.discourse.org/)

**Comment by ghost** [comment]
Discourse looks very nice.

**Comment by Cldfire** [comment]
Looks great, will add to list.
