### ISSUE TITLE
Feature Suggestions & Ideas

### ISSUE THREAD

**Issue by ghost** [Cldfire/Forum-Notifier#26]
Hey,
Please comment below for some suggestions and ideas for new features! I will go ahead and post some myself below as well.

Thanks for contributing to the project by sharing your ideas!

**Comment by ghost** [comment]
Hey, here are some ideas:
- Post:Rating Ratio
- Change status message.
- Stats.
- Allow changing the request interval time.
- Automated PM (besides Spigot)
- Change avatar
- Update account details (location, job, etc).
- A “styler” to change colors or let others pick their own theme would be nice.
- Pie chart showing which sites you have the most posts / ratings on
- Changing avatar.
- For all of these things make it so you can pick which sites to do it on and which to not do it on. Like, some sites I have Saphiria and some I have my personal name. So I would not want to bulk change all of the settings.
- Change signature.
- When someone buys his/her premium resource (like done here https://www.spigotmc.org/resources/spigot-pm-auto-send.3618/)
- Refresh every 30 seconds (or allow user to change the time, but make it so on Spigot it is always 1min).

**Comment by Cldfire** [comment]
test

**Comment by Saphiria** [comment]
test

**Comment by Cldfire** [comment]
test

**Comment by Cldfire** [comment]
test

**Comment by Cldfire** [comment]
test
