### ISSUE TITLE
Mojang.com

### ISSUE THREAD

**Issue by ghost** [Cldfire/Forum-Notifier#28]
Possibly give a notification when a new blog post is released on Mojang.com? Sorta like the GitHub addition.

**Comment by Cldfire** [comment]
Nah, that's completely outside the scope of this project, as it's not something you register an account on.

Such a thing would belong in Blog Notifier :D

**Comment by ghost** [comment]
@Cldfire, what about letting us subscribe to something via RSS?

**Comment by Cldfire** [comment]
I can only see that happening if it's a feed for a forums site or something like that (and most forums wouldn't make that necessary).

**Comment by ghost** [comment]
@Cldfire ah, okay. RSS would be nice for blogs, such as the [Mojang](mojang.com) or [Robinhood](http://blog.robinhood.com) blog. I (and others) often find it hard to keep up with the posts, this would be a nice addition, but I do know it doesn't even make the to-do list. Just a **future** idea.
